spring.jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL92Dialect
    hibernate.ddl-auto: update

spring:
    application.name: booking_service
    # config.import: optional:configserver:${CONFIG_SERVER_URL}

eureka.client:
    region: default
    registryFetchIntervalSeconds: 75
    # serviceUrl.defaultZone: ${SERVICE_DISCOVERER_URL}/eureka/

