spring:
  application:
    name: fbk-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

spring.config.import: optional:configserver:https://fbk-config-server.herokuapp.com

eureka:
  client:
    serviceUrl.defaultZone: http://fbk-service-discoverer.herokuapp.com/eureka/
    region: default
    registryFetchIntervalSeconds: 40
