spring:
  application:
    name: fbk-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    # serviceUrl.defaultZone: http://localhost:2222/eureka
    region: default
    registryFetchIntervalSeconds: 60
