spring:
  application:
    name: fbk-service-discoverer

eureka:
  client:
    # serviceUrl.defaultZone: https://fbk-service-discoverer.herokuapp.com/eureka/
    register-with-eureka: false
    fetch-registry: false
